#!/usr/bin/env python3
"""Generate the fixed f32 golden-angle kernel used by raster AO and soft shadows."""
import math
import struct
from pathlib import Path


def f32(value):
    return struct.unpack("f", struct.pack("f", value))[0]


def source():
    rows = []
    for index in range(128):
        fi = f32(index + 0.5)
        angle = f32(fi * f32(2.3999632))
        radius = f32(math.sqrt(f32(fi / 128.0)))
        x = f32(f32(math.cos(angle)) * radius)
        y = f32(f32(math.sin(angle)) * radius)
        rows.append(f"    vec2<f32>({x:.9g}, {y:.9g}),")
    return "// Generated by scripts/generate_ao_kernel.py; fixed 128-point disk.\n" + \
        "const AO_DISK = array<vec2<f32>, 128>(\n" + "\n".join(rows) + "\n);\n"


if __name__ == "__main__":
    target = Path(__file__).resolve().parent.parent / "crates/molar_vis_core/src/render/shaders/ao_kernel.wgsl"
    target.write_text(source())
